packages:
  - packages/*
  - __tests__
  - __tests__/*

onlyBuiltDependencies:
  - es5-ext
  - esbuild
  - sharp
  - workerd

catalog:
  "@cloudflare/workers-types": "^4.20260317.1"
  "@types/react": "^19.2.14"
  react: "^19.2.4"
  react-dom: "^19.2.4"
  tsdown: "^0.21.6"
  vite: "^6.4.1"
  wrangler: "^4.77.0"
