packages:
  - packages/*
  - __tests__
  - __tests__/*

allowBuilds:
  es5-ext: true
  esbuild: true
  sharp: true
  workerd: true

catalog:
  "@cloudflare/workers-types": "^4.20260317.1"
  "@types/react": "^19.2.14"
  react: "^19.2.4"
  react-dom: "^19.2.4"
  tsdown: "^0.21.6"
  vite: "^6.4.1"
  wrangler: "^4.77.0"

engineStrict: true
strictPeerDependencies: true
shellEmulator: true
preferWorkspacePackages: true
linkWorkspacePackages: true
enablePrePostScripts: true
