name: Build reusable

on:
  workflow_call:
    inputs:
      skipInstallBuild:
        required: false
        description: "Whether to skip $ pnpm install && pnpm run build"
        type: boolean
      nodeVersion:
        required: false
        description: "Version of Node.js to use"
        type: string
      afterBuild:
        required: false
        description: "Additional steps to run"
        type: string

# env:
#   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#   TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
#   TURBO_REMOTE_ONLY: true

jobs:
  build:
    name: ⬣ Build on Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.nodeVersion || '["22.x"]') }}
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        if: ${{ inputs.skipInstallBuild == false }}
        run: pnpm install
      - name: Build
        if: ${{ inputs.skipInstallBuild == false }}
        run: pnpm run build
      - name: Run after build
        if: ${{ inputs.afterBuild != '' }}
        run: /bin/bash -c "${{ inputs.afterBuild }}"
